In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'pandas'

In [ ]:
df = pd.read_csv('adult.csv')
df.head()

In [3]:
df.shape

(32560, 15)

<h4 style="color:blue">Reanming the columns with the given names</h4>

In [4]:
df.columns = ['Age', 'Workclass', 'Fnlwgt','Education','education_num','marital_status','occupation','relationship','race','sex','capital_gain','capital_loss','hours_per_week', 'native_country','income' ]
df.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

<h4 style="color:blue">checking and removing null value</h4>

In [5]:
df.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

<h4 style="color:blue">checking the data types of the columns</h4>

In [6]:
df.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income            object
dtype: object

<h4 style="color:blue">Here we are first spliting the data to x = input and y = output</h4>
<h4 style="color:blue">After that we can perform chage in data type from object to integer or float</h4>

In [7]:
x = df.iloc[:,:-1]
#  it is equal to 
# x= df[['sepal.length','sepal.width','petal.length','petal.width']]
y = df.iloc[:,-1]
print(type(x))
print(type(y))
print(x.shape)
print(y.shape)

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>
(32560, 14)
(32560,)


In [8]:
x.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  
0             0             0              13   United-States  
1             0             0              40   United-States  
2             0             0              40   United-States  
3             0             0              40            Cuba  
4             0             0              40   United-States

In [9]:
y.head()

0     <=50K
1     <=50K
2     <=50K
3     <=50K
4     <=50K
Name: income, dtype: object

<h4 style="color:blue">Finding the object columns in X (input data frame)</h4>

In [10]:
cat_cols = [i for i in x.columns if x[i].dtypes=='object']
cat_cols

['Workclass',
 'Education',
 'marital_status',
 'occupation',
 'relationship',
 'race',
 'sex',
 'native_country']

In [11]:
from sklearn.preprocessing import LabelEncoder

In [12]:
lb = LabelEncoder()
for i in cat_cols:
    x[i] = lb.fit_transform(x[i])

<h4 style="color:blue">Converting them into integers data type</h4>

In [13]:
x.dtypes

Age               int64
Workclass         int32
Fnlwgt            int64
Education         int32
education_num     int64
marital_status    int32
occupation        int32
relationship      int32
race              int32
sex               int32
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int32
dtype: object

In [14]:
y.dtypes

dtype('O')

<h4 style="color:blue">Spliting the data into training and test data</h4>

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(x_test.shape)

(26048, 14)
(6512, 14)
(26048,)
(6512, 14)


<h4 style="color:blue">Creating confusion matrix and Classification report and Percentage Of Missclasification of models function</h4>
<b>Percentage Of Missclasification = (FP + FN)/(TP + FP + FN + TN)</b><br>
<b>Also Percentage Of Missclasification = 1 - Accuracy</b><br>

In [16]:
from sklearn.metrics import confusion_matrix,classification_report

In [17]:
from sklearn.metrics import accuracy_score
def gen_metrics(y_test,y_predict):
    cm = confusion_matrix(y_test,y_predict)
    print('confusion metrics \n',cm)
    print('classification report\n ',classification_report(y_test,y_predict))
    print('acuracy ', accuracy_score(y_test,y_predict))
    pom = 1 - accuracy_score(y_test,y_predict)
    print('Percentage Of Missclasification ', pom)
   

<h4 style = "color:blue">Validating Precision, Recall, F1-score, Accuracy for each model</h4> 
<h4 style = "color:blue">IMportant Formulas</h4> 

<b>1) Precision - TP/(TP+FP), TN/(TN+FN)</b><br>
From all the positively predicted cases, how many are actually positive<br>
From all the negatively predicted cases, how many are actually negative

<b>2) Recall - TP/(TP+FN), TN/(TN+FP)</b><br>
From all the actual positive cases, how many has the ML model predicted positive<br>
From all the actual negative cases, how many has the ML model predicted negative<br>

<b>3) F1-Score - 2 * Precision * Recall /( Precision + Recall)</b><br>
It is the Harmonic mean between Precision and Recall<br>

<b>4) Accuracy - (TP+TN)/(TP+FN+FP+TN) </b><br>
Out of all the values, how many the model has predicted correctly<br>
<br>
using the above formula we can verify from confusion matrix and classification report<br>
[[TP FN]<br>
[FP TN]]<br>

<h4 style="color:blue">1. Decision Tree</h4>

In [18]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
m1 = DecisionTreeClassifier(criterion='gini',max_depth = 10,min_samples_split=25)
m1.fit(x_train,y_train)

DecisionTreeClassifier(max_depth=10, min_samples_split=25)

In [21]:
print('training score ',m1.score(x_train,y_train))
print('testing score ',m1.score(x_test,y_test))

training score  0.8663621007371007
testing score  0.855958230958231


In [22]:
y_predict_m1 = m1.predict(x_test)
print(y_predict_m1)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [23]:
gen_metrics(y_test,y_predict_m1)
print('testing score ',m1.score(x_test,y_test))

confusion metrics 
 [[4654  393]
 [ 545  920]]
classification report
                precision    recall  f1-score   support

       <=50K       0.90      0.92      0.91      5047
        >50K       0.70      0.63      0.66      1465

    accuracy                           0.86      6512
   macro avg       0.80      0.78      0.79      6512
weighted avg       0.85      0.86      0.85      6512

acuracy  0.855958230958231
Percentage Of Missclasification  0.14404176904176902
testing score  0.855958230958231


<h4 style = "color:blue">checking Precision, Recall, F1-score, Accuracy from cnfusion matrix for decision tree</h4> 

In [24]:
p = 4739/(4739+730)
r = 4739/(4739+224)
a = (4739 + 819)/(4739+730+819+224)
f = 2*p*r/(p+r)

print('precision ', p)
print('Recall ', r)
print('Accuracy ', a)
print('F1-score ', f)


precision  0.8665203876394222
Recall  0.9548660084626234
Accuracy  0.8535012285012284
F1-score  0.9085506134969326


<h4 style="color:blue">2. Random Forest Classifier</h4>

In [25]:
from sklearn.ensemble import RandomForestClassifier

In [26]:
m2 = RandomForestClassifier(n_estimators=50,criterion='entropy',max_depth=10,min_samples_split=12)
m2.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=10, min_samples_split=12,
                       n_estimators=50)

In [27]:
print("training score ", m2.score(x_train,y_train))
print("testing score ", m2.score(x_test,y_test))

training score  0.8629837223587223
testing score  0.8636363636363636


In [28]:
y_predict_m2 = m2.predict(x_test)
print(y_predict_m2)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [29]:
gen_metrics(y_test,y_predict_m2)
print('testing score ',m2.score(x_test,y_test))

confusion metrics 
 [[4823  224]
 [ 664  801]]
classification report
                precision    recall  f1-score   support

       <=50K       0.88      0.96      0.92      5047
        >50K       0.78      0.55      0.64      1465

    accuracy                           0.86      6512
   macro avg       0.83      0.75      0.78      6512
weighted avg       0.86      0.86      0.85      6512

acuracy  0.8636363636363636
Percentage Of Missclasification  0.13636363636363635
testing score  0.8636363636363636


<h4 style = "color:blue">checking Precision, Recall, F1-score, Accuracy from cnfusion matrix for random forest classifer</h4>

In [30]:
p = 4766/(4766+737)
r = 4766/(4739+197)
a = (4766 + 812)/(4766 + 812+197+737)
f = 2*p*r/(p+r)

print('precision ', p)
print('Recall ', r)
print('Accuracy ', a)
print('F1-score ', f)

precision  0.8660730510630565
Recall  0.9655591572123177
Accuracy  0.8565724815724816
F1-score  0.9131142829772967


<h4 style="color:blue">3. KNN</h4>

In [31]:
from sklearn.neighbors import KNeighborsClassifier

In [32]:
m3 = KNeighborsClassifier(n_neighbors= 13)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=13)

In [33]:
print('training score ', m3.score(x_train,y_train))
print('testing score ', m3.score(x_test,y_test))

training score  0.8060503685503686
testing score  0.8068181818181818


In [34]:
y_predict_m3 = m3.predict(x_test)
print(y_predict_m3)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' <=50K']


In [35]:
gen_metrics(y_test,y_predict_m3)
print('training score ', m3.score(x_test,y_test))

confusion metrics 
 [[4906  141]
 [1117  348]]
classification report
                precision    recall  f1-score   support

       <=50K       0.81      0.97      0.89      5047
        >50K       0.71      0.24      0.36      1465

    accuracy                           0.81      6512
   macro avg       0.76      0.60      0.62      6512
weighted avg       0.79      0.81      0.77      6512

acuracy  0.8068181818181818
Percentage Of Missclasification  0.19318181818181823
training score  0.8068181818181818


<h4 style = "color:blue">checking Precision, Recall, F1-score, Accuracy from cnfusion matrix for KNN</h4>

In [36]:
p = 4800/(4800+1181)
r = 4800/(4800+163)
a = (4800 + 368)/(4800 + 368+163+1181)
f = 2*p*r/(p+r)

print('precision ', p)
print('Recall ', r)
print('Accuracy ', a)
print('F1-score ', f)

precision  0.8025413810399599
Recall  0.9671569615152126
Accuracy  0.7936117936117936
F1-score  0.8771929824561403


<h4 style="color:blue">4.Logistic Regression</h4>

In [37]:
from sklearn.linear_model import LogisticRegression

In [38]:
m4 = LogisticRegression(max_iter=1000)
m4.fit(x_train,y_train)

LogisticRegression(max_iter=1000)

In [39]:
print('training score ', m4.score(x_train,y_train))
print('testing score ', m4.score(x_test,y_test))

training score  0.785127457002457
testing score  0.79745085995086


In [40]:
y_predict_m4 = m4.predict(x_test)
print(y_predict_m4)

[' <=50K' ' <=50K' ' <=50K' ... ' <=50K' ' >50K' ' >50K']


In [41]:
gen_metrics(y_test,y_predict_m4)
print('testing score ',m4.score(x_test,y_test))

confusion metrics 
 [[4740  307]
 [1012  453]]
classification report
                precision    recall  f1-score   support

       <=50K       0.82      0.94      0.88      5047
        >50K       0.60      0.31      0.41      1465

    accuracy                           0.80      6512
   macro avg       0.71      0.62      0.64      6512
weighted avg       0.77      0.80      0.77      6512

acuracy  0.79745085995086
Percentage Of Missclasification  0.20254914004914004
testing score  0.79745085995086


<h4 style = "color:blue">checking Precision, Recall, F1-score, Accuracy from cnfusion matrix for logistic regression</h4>

In [42]:
p = 4694/(4694+1099)
r = 4694/(4694+269)
a = (4694 + 450)/(4694 + 450+269+1099)
f = 2*p*r/(p+r)

print('precision ', p)
print('Recall ', r)
print('Accuracy ', a)
print('F1-score ', f)

precision  0.8102882789573623
Recall  0.9457989119484183
Accuracy  0.7899262899262899
F1-score  0.8728151729267386


<h4 style="color:blue">5.SVM</h4>

In [43]:
from sklearn.svm import SVC

In [ ]:
m5 = SVC(kernel='linear', C=1)
m5.fit(x_train,y_train)

In [ ]:
print('training score ',m5.score(x_train,y_train))
print('testing score ',m5.score(x_test,y_test))

In [ ]:
y_predict_m5 = m5.predict(x_test)
print(y_predict_m5)

In [ ]:
gen_metrics(y_test,y_predict_m5)
print('testing score ',m5.score(x_test,y_test))

<h4 style = "color:blue">checking Precision, Recall, F1-score, Accuracy from cnfusion matrix for SVC</h4>

<h4 style = "color:blue">Model with best Accuracy</h4>
<b>This may be change as train test split of the data set is taken as random<b>
<h4 style = "color:blue">We can clearly see the Random Forest Classifer has the highest accuracy</h4>

